### PR TITLE
Change grpc consul check

### PR DESCRIPTION
**Pull request by maxtany**

### CODE REVIEW

**Comment by oliora** [comment]
Any particular reason why you’ve closed this?

**Comment by maxtany** [comment]
@oliora hi, Thank you for looking on that, but the PR was made by mistake - it is not arranged as it should and actually I'm not sure you want to have this behavior. If you are interesting in adding GRPC check to ppconsul I  ill be more than happy to make an appropriate PR. What do you think ?

**Comment by oliora** [comment]
@maxtany it is be a useful feature so if you have time for this then please add it!

**Comment by maxtany** [comment]
@oliora Thank you. I will

**Pull request closed without merging**
